version: '3.9'
services:
  mysql-db:
    image: mysql:latest
    ports: 
      - "3306:3306"
    container_name: my-mysql
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD:mysql
       - MYSQL_USER=root
       - MYSQL_PASSWORD:mysql
       - MYSQL_DATABASE=dbmysql

  web:
    build: .
    volumes:
      - .:/app-apipython
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  